name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv --python $(which python)
          pipenv install flask
          pipenv install mutagen
          pipenv install Werkzeug
      - name: Test with pytest
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv run python -m pytest
