name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install MongoDB client on the runner
      - name: Install MongoDB client
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb-clients

      # Wait for MongoDB to initialize
      - name: Wait for MongoDB to start
        run: sleep 20

      # Test MongoDB connection
      - name: Test MongoDB connection
        run: |
          mongo --host localhost --username admin --password password --eval "db.runCommand({ping: 1})"

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd web-app
          pipenv install --deploy --system

      # Run pytest
      - name: Test with web-app using pytest
        env:
          MONGO_HOST: localhost
          MONGO_PORT: 27017
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_DB_NAME: voice_data
        run: |
          cd web-app
          pipenv install pytest
          pipenv run pytest


