name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # this is important so git fetches all history.. the actions/checkout by default fetches all history as one commit which throws off stats
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv --python $(which python)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv --python $(which python)
          cd web-app
          pipenv install flask
          pipenv install mutagen
          pipenv install Werkzeug
          pipenv install -r requirements.txt
      - name: Test with pytest
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv run python -m pytest
