name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd web-app
          pipenv install --deploy --system
      
      - name: Wait for MongoDB to be ready
        run: sleep 20
      
      - name: Test connection to MongoDB
        run: |
          mongo --host mongo --eval "db.runCommand({ping: 1})"
      
      - name: Run Tests
        env:
          MONGO_HOST: mongo
          MONGO_PORT: 27017
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_DB_NAME: voice_data
        run: |
          cd web-app
          pipenv run pytest
      
      - name: Show MongoDB logs
        if: failure()
        run: docker logs $(docker ps -q --filter ancestor=mongo)
