name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          cd web-app
          pipenv install --deploy --system
      - name: Test with web-app with pytest
        run: |
          cd web-app
          pipenv install pytest
          pipenv run pytest
      - name: Test with ml-client with pytest
        run: |
          cd machine-learning-client
          pipenv install pytest
          pipenv run pytest
