name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: "3.10"
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Install dependencies
        run: |
          cd web-app
          pipenv install flask
          pipenv install mutagen
          pipenv install Werkzeug
          pipenv install -r requirements.txt
      - name: Test with pytest
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv run python -m pytest
